In [4]:
import pandas as pd
import numpy as np
import os
os.getcwd()

'm:\\Portofolio_projects\\H&M_retail_Intelligence\\python\\data_cleaning'

In [5]:
os.listdir()

['claen_articles.ipynb',
 'clean_customers.ipynb',
 'clean_transactions.ipynb',
 'sample_dataset.py']

In [6]:
print(os.getcwd())

m:\Portofolio_projects\H&M_retail_Intelligence\python\data_cleaning

In [7]:
print(os.listdir())

['claen_articles.ipynb', 'clean_customers.ipynb', 'clean_transactions.ipynb', 'sample_dataset.py']

In [8]:
from pathlib import Path

for path in Path(".").rglob("articles_sample.csv"):
    print(path)

In [9]:
articles=pd.read_csv("../../dataset/processed/articles_sample.csv")

In [10]:
print(articles.head(20))

    article_id  product_code                  prod_name  product_type_no  \
0    108775015        108775                  Strap top              253
1    108775044        108775                  Strap top              253
2    108775051        108775              Strap top (1)              253
3    110065001        110065          OP T-shirt (Idro)              306
4    110065002        110065          OP T-shirt (Idro)              306
5    110065011        110065          OP T-shirt (Idro)              306
6    111565001        111565        20 den 1p Stockings              304
7    111586001        111586  Shape Up 30 den 1p Tights              273
8    111593001        111593   Support 40 den 1p Tights              304
9    111609001        111609          200 den 1p Tights              304
10   114428030        114428          Alice BANDEAU 2-p              306
11   116379047        116379          Frugan longsleeve              254
12   118458004        118458       Jerry jogger bottoms              272
13   118458028        118458       Jerry jogger bottoms              272
14   118458029        118458       Jerry jogger bottoms              272
15   118458038        118458       Jerry jogger bottoms              272
16   118458039        118458       Jerry jogger bottoms              272
17   120129001        120129               Babette long              273
18   120129014        120129               Babette long              273
19   120129018        120129               Babette long              273

   product_type_name  product_group_name  graphical_appearance_no  \
0           Vest top  Garment Upper body                  1010016
1           Vest top  Garment Upper body                  1010016
2           Vest top  Garment Upper body                  1010017
3                Bra           Underwear                  1010016
4                Bra           Underwear                  1010016
5                Bra           Underwear                  1010016
6   Underwear Tights      Socks & Tights                  1010016
7    Leggings/Tights  Garment Lower body                  1010016
8   Underwear Tights      Socks & Tights                  1010016
9   Underwear Tights      Socks & Tights                  1010016
10               Bra           Underwear                  1010016
11               Top  Garment Upper body                  1010016
12          Trousers  Garment Lower body                  1010010
13          Trousers  Garment Lower body                  1010016
14          Trousers  Garment Lower body                  1010010
15          Trousers  Garment Lower body                  1010010
16          Trousers  Garment Lower body                  1010010
17   Leggings/Tights  Garment Lower body                  1010016
18   Leggings/Tights  Garment Lower body                  1010010
19   Leggings/Tights  Garment Lower body                  1010016

   graphical_appearance_name  colour_group_code colour_group_name  ...  \
0                      Solid                  9             Black  ...
1                      Solid                 10             White  ...
2                     Stripe                 11         Off White  ...
3                      Solid                  9             Black  ...
4                      Solid                 10             White  ...
5                      Solid                 12       Light Beige  ...
6                      Solid                  9             Black  ...
7                      Solid                  9             Black  ...
8                      Solid                  9             Black  ...
9                      Solid                  9             Black  ...
10                     Solid                  6        Light Grey  ...
11                     Solid                 73         Dark Blue  ...
12                   Melange                  7              Grey  ...
13                     Solid                  9             Black  ...
14                   Melange                  8         Dark Grey  ...
15                   Melange                  9             Black  ...
16                   Melange                 73         Dark Blue  ...
17                     Solid                  9             Black  ...
18                   Melange                  9             Black  ...
19                     Solid                 43          Dark Red  ...

    department_name index_code        index_name index_group_no  \
0      Jersey Basic          A        Ladieswear              1
1      Jersey Basic          A        Ladieswear              1
2      Jersey Basic          A        Ladieswear              1
3    Clean Lingerie          B  Lingeries/Tights              1
4    Clean Lingerie          B  Lingeries/Tights              1
5    Clean Lingerie          B  Lingeries/Tights              1
6      Tights basic          B  Lingeries/Tights              1
7      Tights basic          B  Lingeries/Tights              1
8      Tights basic          B  Lingeries/Tights              1
9      Tights basic          B  Lingeries/Tights              1
10  Casual Lingerie          B  Lingeries/Tights              1
11     Jersey Basic          A        Ladieswear              1
12     Jersey Basic          F          Menswear              3
13     Jersey Basic          F          Menswear              3
14     Jersey Basic          F          Menswear              3
15     Jersey Basic          F          Menswear              3
16     Jersey Basic          F          Menswear              3
17           Jersey          A        Ladieswear              1
18           Jersey          A        Ladieswear              1
19           Jersey          A        Ladieswear              1

    index_group_name section_no                    section_name  \
0         Ladieswear         16          Womens Everyday Basics
1         Ladieswear         16          Womens Everyday Basics
2         Ladieswear         16          Womens Everyday Basics
3         Ladieswear         61                 Womens Lingerie
4         Ladieswear         61                 Womens Lingerie
5         Ladieswear         61                 Womens Lingerie
6         Ladieswear         62  Womens Nightwear, Socks & Tigh
7         Ladieswear         62  Womens Nightwear, Socks & Tigh
8         Ladieswear         62  Womens Nightwear, Socks & Tigh
9         Ladieswear         62  Womens Nightwear, Socks & Tigh
10        Ladieswear         61                 Womens Lingerie
11        Ladieswear         16          Womens Everyday Basics
12          Menswear         26                   Men Underwear
13          Menswear         26                   Men Underwear
14          Menswear         26                   Men Underwear
15          Menswear         26                   Men Underwear
16          Menswear         26                   Men Underwear
17        Ladieswear          8                            Mama
18        Ladieswear          8                            Mama
19        Ladieswear          8                            Mama

   garment_group_no  garment_group_name  \
0              1002        Jersey Basic
1              1002        Jersey Basic
2              1002        Jersey Basic
3              1017   Under-, Nightwear
4              1017   Under-, Nightwear
5              1017   Under-, Nightwear
6              1021    Socks and Tights
7              1021    Socks and Tights
8              1021    Socks and Tights
9              1021    Socks and Tights
10             1017   Under-, Nightwear
11             1002        Jersey Basic
12             1002        Jersey Basic
13             1002        Jersey Basic
14             1002        Jersey Basic
15             1002        Jersey Basic
16             1002        Jersey Basic
17             1005        Jersey Fancy
18             1005        Jersey Fancy
19             1005        Jersey Fancy

                                          detail_desc
0             Jersey top with narrow shoulder straps.
1             Jersey top with narrow shoulder straps.
2             Jersey top with narrow shoulder straps.
3   Microfibre T-shirt bra with underwired, moulde...
4   Microfibre T-shirt bra with underwired, moulde...
5   Microfibre T-shirt bra with underwired, moulde...
6   Semi shiny nylon stockings with a wide, reinfo...
7   Tights with built-in support to lift the botto...
8   Semi shiny tights that shape the tummy, thighs...
9                     Opaque matt tights. 200 denier.
10  Two soft bandeau bras in soft jersey with side...
11  Fitted top in soft stretch jersey with a wide ...
12  Trousers in sweatshirt fabric with an elastica...
13  Trousers in sweatshirt fabric with an elastica...
14  Trousers in sweatshirt fabric with an elastica...
15  Trousers in sweatshirt fabric with an elastica...
16  Trousers in sweatshirt fabric with an elastica...
17  Leggings in soft jersey with a wide panel at t...
18  Leggings in soft jersey with a wide panel at t...
19  Leggings in soft jersey with a wide panel at t...

[20 rows x 25 columns]

In [11]:
articles.shape

(57417, 25)

In [12]:
pd.set_option('display.max_columns', None)

In [13]:
pd.set_option('display.max_colwidth', None)

In [16]:
articles = pd.read_csv("../../dataset/processed/articles_sample.csv")

In [19]:
articles.head()

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,perceived_colour_value_id,perceived_colour_value_name,perceived_colour_master_id,perceived_colour_master_name,department_no,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,4,Dark,5,Black,1676,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,3,Light,9,White,1676,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,1,Dusty Light,9,White,1676,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,4,Dark,5,Black,1339,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,3,Light,9,White,1339,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort."

In [20]:
print("_",60)

_ 60

In [21]:
print("artcles dt ooverview")

artcles dt ooverview

In [22]:
print(articles.info())

<class 'pandas.DataFrame'>
RangeIndex: 57417 entries, 0 to 57416
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   article_id                    57417 non-null  int64
 1   product_code                  57417 non-null  int64
 2   prod_name                     57417 non-null  str
 3   product_type_no               57417 non-null  int64
 4   product_type_name             57417 non-null  str
 5   product_group_name            57417 non-null  str
 6   graphical_appearance_no       57417 non-null  int64
 7   graphical_appearance_name     57417 non-null  str
 8   colour_group_code             57417 non-null  int64
 9   colour_group_name             57417 non-null  str
 10  perceived_colour_value_id     57417 non-null  int64
 11  perceived_colour_value_name   57417 non-null  str
 12  perceived_colour_master_id    57417 non-null  int64
 13  perceived_colour_master_name  57417 non-null  str
 14  department_no                 57417 non-null  int64
 15  department_name               57417 non-null  str
 16  index_code                    57417 non-null  str
 17  index_name                    57417 non-null  str
 18  index_group_no                57417 non-null  int64
 19  index_group_name              57417 non-null  str
 20  section_no                    57417 non-null  int64
 21  section_name                  57417 non-null  str
 22  garment_group_no              57417 non-null  int64
 23  garment_group_name            57417 non-null  str
 24  detail_desc                   57202 non-null  str
dtypes: int64(11), str(14)
memory usage: 11.0 MB
None

In [25]:
missing = pd.DataFrame({
    "Missing Values": articles.isnull().sum(),
    "Percentage": (
        articles.isnull().sum() / len(articles) * 100
    ).round(2)
})

missing.sort_values("Missing Values", ascending=False)

                              Missing Values  Percentage
detail_desc                              215        0.37
product_code                               0        0.00
prod_name                                  0        0.00
product_type_no                            0        0.00
product_type_name                          0        0.00
product_group_name                         0        0.00
graphical_appearance_no                    0        0.00
graphical_appearance_name                  0        0.00
article_id                                 0        0.00
colour_group_code                          0        0.00
colour_group_name                          0        0.00
perceived_colour_value_name                0        0.00
perceived_colour_value_id                  0        0.00
perceived_colour_master_name               0        0.00
department_no                              0        0.00
department_name                            0        0.00
perceived_colour_master_id                 0        0.00
index_code                                 0        0.00
index_name                                 0        0.00
index_group_name                           0        0.00
index_group_no                             0        0.00
section_no                                 0        0.00
section_name                               0        0.00
garment_group_no                           0        0.00
garment_group_name                         0        0.00

In [27]:
print("duplicates", articles.duplicated().sum())

duplicates 0

In [28]:
print("duplicate article_id", articles["article_id"].duplicated().sum())

duplicate article_id 0

In [30]:
print("duplicate product_code", articles["product_code"].duplicated().sum())

duplicate product_code 29187

In [31]:
articles.dtypes

article_id                      int64
product_code                    int64
prod_name                         str
product_type_no                 int64
product_type_name                 str
product_group_name                str
graphical_appearance_no         int64
graphical_appearance_name         str
colour_group_code               int64
colour_group_name                 str
perceived_colour_value_id       int64
perceived_colour_value_name       str
perceived_colour_master_id      int64
perceived_colour_master_name      str
department_no                   int64
department_name                   str
index_code                        str
index_name                        str
index_group_no                  int64
index_group_name                  str
section_no                      int64
section_name                      str
garment_group_no                int64
garment_group_name                str
detail_desc                       str
dtype: object

In [32]:
articles.describe()

,article_id,product_code,product_type_no,graphical_appearance_no,colour_group_code,perceived_colour_value_id,perceived_colour_master_id,department_no,index_group_no,section_no,garment_group_no
count,5.741700e+04,57417.000000,57417.000000,5.741700e+04,57417.000000,57417.000000,57417.000000,57417.000000,57417.000000,57417.000000,57417.000000
mean,7.082903e+08,708290.317310,238.495672,1.009485e+06,29.775084,3.211157,7.862689,3712.591846,2.730237,39.260132,1010.537611
std,1.234050e+08,123405.034526,72.275588,2.308119e+04,27.295609,1.536457,5.305633,2565.750925,4.483704,23.613781,6.562567
min,1.087750e+08,108775.000000,-1.000000,-1.000000e+00,-1.000000,-1.000000,-1.000000,1201.000000,1.000000,2.000000,1001.000000
25%,6.365850e+08,636585.000000,252.000000,1.010010e+06,9.000000,2.000000,4.000000,1640.000000,1.000000,15.000000,1005.000000
50%,7.148720e+08,714872.000000,262.000000,1.010016e+06,12.000000,4.000000,5.000000,2033.000000,1.000000,46.000000,1010.000000
75%,7.987790e+08,798779.000000,272.000000,1.010016e+06,51.000000,4.000000,11.000000,5828.000000,3.000000,60.000000,1017.000000
max,9.562170e+08,956217.000000,762.000000,1.010029e+06,93.000000,7.000000,20.000000,9989.000000,26.000000,97.000000,1025.000000

In [34]:
#categorical columns
articles.describe(include="object")

C:\Users\Medha Parag Patil\AppData\Local\Temp\ipykernel_21612\2686688537.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  articles.describe(include="object")

,prod_name,product_type_name,product_group_name,graphical_appearance_name,colour_group_name,perceived_colour_value_name,perceived_colour_master_name,department_name,index_code,index_name,index_group_name,section_name,garment_group_name,detail_desc
count,57417,57417,57417,57417,57417,57417,57417,57417,57417,57417,57417,57417,57417,57202
unique,27970,119,18,30,50,8,20,245,10,10,5,56,21,26269
top,Mike tee,Dress,Garment Upper body,Solid,Black,Dark,Black,Jersey,A,Ladieswear,Ladieswear,Womens Everyday Collection,Jersey Fancy,"Socks in a soft, jacquard-knit cotton blend with elasticated tops."
freq,59,6466,23493,29149,14451,24457,14385,3220,18738,18738,28902,5802,11177,102

In [36]:
#Unique Values
articles.nunique().sort_values(ascending=False)

article_id                      57417
product_code                    28230
prod_name                       27970
detail_desc                     26269
department_no                     294
department_name                   245
product_type_no                   120
product_type_name                 119
section_no                         57
section_name                       56
colour_group_name                  50
colour_group_code                  50
graphical_appearance_no            30
graphical_appearance_name          30
garment_group_no                   21
garment_group_name                 21
perceived_colour_master_id         20
perceived_colour_master_name       20
product_group_name                 18
index_code                         10
index_name                         10
perceived_colour_value_id           8
perceived_colour_value_name         8
index_group_name                    5
index_group_no                      5
dtype: int64

In [39]:
#immportant columns
articles["product_group_name"].value_counts()

product_group_name
Garment Upper body       23493
Garment Lower body       10829
Garment Full body         7436
Accessories               5381
Underwear                 3732
Shoes                     2317
Swimwear                  2120
Socks & Tights            1105
Nightwear                  867
Unknown                     82
Bags                        17
Cosmetic                    14
Items                       11
Underwear/nightwear          5
Furniture                    3
Garment and Shoe care        3
Interior textile             1
Stationery                   1
Name: count, dtype: int64

In [40]:
articles["garment_group_name"].value_counts()

garment_group_name
Jersey Fancy                     11177
Accessories                       5499
Under-, Nightwear                 4605
Knitwear                          4284
Blouses                           4253
Jersey Basic                      4160
Trousers                          4008
Dresses Ladies                    3637
Shoes                             2260
Outdoor                           2045
Swimwear                          1978
Trousers Denim                    1798
Unknown                           1747
Socks and Tights                  1037
Skirts                            1015
Shorts                             980
Shirts                             961
Dressed                            581
Special Offers                     478
Woven/Jersey/Knitted mix Baby      471
Dresses/Skirts girls               443
Name: count, dtype: int64

In [41]:
articles["department_name"].value_counts()

department_name
Jersey                       3220
Knitwear                     2286
Trouser                      1892
Blouse                       1892
Swimwear                     1741
                             ...
Girls Projects                  1
Jersey inactive from S.6        1
Baby Girl Local Relevance       1
EQ Divided Blue                 1
Accessories Other               1
Name: count, Length: 245, dtype: int64

In [42]:
articles["section_name"].value_counts()

section_name
Womens Everyday Collection        5802
Divided Collection                5564
Womens Lingerie                   2785
Womens Tailoring                  2615
Womens Casual                     2106
Womens Small accessories          2089
Womens Trend                      1777
H&M+                              1673
Womens Swimwear, beachwear        1598
Divided Projects                  1571
Men Underwear                     1520
Womens Shoes                      1487
Ladies H&M Sport                  1476
Divided Basics                    1396
Young Girl                        1348
Womens Everyday Basics            1310
Womens Nightwear, Socks & Tigh    1255
Mama                              1207
Womens Big accessories            1162
Baby Essentials & Complements     1104
Contemporary Smart                1104
Kids Girl                         1020
Divided Accessories                992
Kids Boy                           947
Ladies Denim                       915
Young Boy                          897
Contemporary Casual                887
Girls Underwear & Basics           876
Contemporary Street                787
Divided Selected                   749
Womens Premium                     652
Womens Jackets                     645
Men Suits & Tailoring              633
Boys Underwear & Basics            582
Kids Outerwear                     520
Men Accessories                    495
Kids & Baby Shoes                  464
Baby Boy                           447
Kids Accessories, Swimwear & D     446
Baby Girl                          376
Denim Men                          330
Men H&M Sport                      308
Special Collections                304
Collaborations                     262
Mens Outerwear                     228
Men Shoes                          161
Divided Asia keys                  153
Kids Sports                        149
Men Project                         59
Men Edition                         48
Kids Local Relevance                42
Men Other 2                         36
Divided Complements Other           28
EQ Divided                          14
Men Other                           12
Ladies Other                         4
Name: count, dtype: int64

In [43]:
articles["colour_group_name"].value_counts()

colour_group_name
Black              14451
White               5453
Dark Blue           5353
Light Pink          2472
Light Beige         2083
Grey                2074
Blue                1805
Beige               1800
Light Blue          1636
Off White           1592
Red                 1579
Greenish Khaki      1549
Dark Grey           1428
Dark Red            1382
Dark Green          1181
Pink                1080
Light Grey           977
Yellow               906
Yellowish Brown      854
Light Orange         853
Gold                 842
Dark Beige           604
Dark Orange          537
Dark Pink            478
Light Yellow         436
Orange               410
Green                384
Light Turquoise      353
Silver               350
Light Green          318
Light Purple         285
Dark Yellow          282
Dark Turquoise       265
Other Pink           242
Turquoise            197
Dark Purple          148
Light Red            118
Greyish Beige        116
Other Yellow         104
Purple                99
Other Orange          73
Other Red             49
Other                 47
Other Green           46
Bronze/Copper         36
Other Blue            30
Other Purple          23
Unknown               20
Transparent           15
Other Turquoise        2
Name: count, dtype: int64

In [44]:
articles["detail_desc"] = (
    articles["detail_desc"]
    .fillna("No Description Available")
)

In [45]:
articles["prod_name"] = (
    articles["prod_name"]
    .fillna("No Name Available")
)

In [46]:
articles.duplicated().sum()

np.int64(0)

In [47]:
articles["article_id"].duplicated().sum()

np.int64(0)

In [48]:
object_cols = articles.select_dtypes(include="object").columns

articles[object_cols] = articles[object_cols].apply(
    lambda col: col.str.strip()
)

C:\Users\Medha Parag Patil\AppData\Local\Temp\ipykernel_21612\1073466670.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = articles.select_dtypes(include="object").columns

In [49]:
articles.info()

<class 'pandas.DataFrame'>
RangeIndex: 57417 entries, 0 to 57416
Data columns (total 25 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   article_id                    57417 non-null  int64
 1   product_code                  57417 non-null  int64
 2   prod_name                     57417 non-null  str
 3   product_type_no               57417 non-null  int64
 4   product_type_name             57417 non-null  str
 5   product_group_name            57417 non-null  str
 6   graphical_appearance_no       57417 non-null  int64
 7   graphical_appearance_name     57417 non-null  str
 8   colour_group_code             57417 non-null  int64
 9   colour_group_name             57417 non-null  str
 10  perceived_colour_value_id     57417 non-null  int64
 11  perceived_colour_value_name   57417 non-null  str
 12  perceived_colour_master_id    57417 non-null  int64
 13  perceived_colour_master_name  57417 non-null  str
 14  department_no                 57417 non-null  int64
 15  department_name               57417 non-null  str
 16  index_code                    57417 non-null  str
 17  index_name                    57417 non-null  str
 18  index_group_no                57417 non-null  int64
 19  index_group_name              57417 non-null  str
 20  section_no                    57417 non-null  int64
 21  section_name                  57417 non-null  str
 22  garment_group_no              57417 non-null  int64
 23  garment_group_name            57417 non-null  str
 24  detail_desc                   57417 non-null  str
dtypes: int64(11), str(14)
memory usage: 11.0 MB

In [50]:
(articles == "").sum()

article_id                      0
product_code                    0
prod_name                       0
product_type_no                 0
product_type_name               0
product_group_name              0
graphical_appearance_no         0
graphical_appearance_name       0
colour_group_code               0
colour_group_name               0
perceived_colour_value_id       0
perceived_colour_value_name     0
perceived_colour_master_id      0
perceived_colour_master_name    0
department_no                   0
department_name                 0
index_code                      0
index_name                      0
index_group_no                  0
index_group_name                0
section_no                      0
section_name                    0
garment_group_no                0
garment_group_name              0
detail_desc                     0
dtype: int64

In [51]:
articles.replace("", np.nan, inplace=True)

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,perceived_colour_value_id,perceived_colour_value_name,perceived_colour_master_id,perceived_colour_master_name,department_no,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,4,Dark,5,Black,1676,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,3,Light,9,White,1676,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,1,Dusty Light,9,White,1676,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,4,Dark,5,Black,1339,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,3,Light,9,White,1339,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulded, lightly padded cups that shape the bust and provide good support. Narrow adjustable shoulder straps and a narrow hook-and-eye fastening at the back. Without visible seams for greater comfort."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57412,949551001,949551,Virgo sweater fast buy,252,Sweater,Garment Upper body,1010016,Solid,9,Black,4,Dark,5,Black,1640,Tops Fancy Jersey,D,Divided,2,Divided,53,Divided Collection,1005,Jersey Fancy,"Short, boxy-style top in sweatshirt fabric made from a cotton blend with dropped shoulders and long sleeves with ribbing at the cuffs. Smocking at the hem. Soft brushed inside."
57413,949551002,949551,Virgo sweater fast buy,252,Sweater,Garment Upper body,1010016,Solid,52,Pink,1,Dusty Light,4,Pink,1640,Tops Fancy Jersey,D,Divided,2,Divided,53,Divided Collection,1005,Jersey Fancy,"Short, boxy-style top in sweatshirt fabric made from a cotton blend with dropped shoulders and long sleeves with ribbing at the cuffs. Smocking at the hem. Soft brushed inside."
57414,952267001,952267,Heavy plain overknee tights 1p,304,Underwear Tights,Socks & Tights,1010013,Other pattern,9,Black,4,Dark,5,Black,3608,Tights basic,B,Lingeries/Tights,1,Ladieswear,62,"Womens Nightwear, Socks & Tigh",1021,Socks and Tights,Fine-knit tights with an elasticated waist that are thinner at the top and more opaque at the bottom giving them the appearance of over-the-knee socks.
57415,953763001,953763,SPORT Malaga tank,253,Vest top,Garment Upper body,1010016,Solid,9,Black,4,Dark,5,Black,1919,Jersey,A,Ladieswear,1,Ladieswear,2,H&M+,1005,Jersey Fancy,Loose-fitting sports vest top in ribbed fast-drying functional fabric made from recycled polyester with a racer back and rounded hem.
57416,956217002,956217,Cartwheel dress,265,Dress,Garment Full body,1010016,Solid,9,Black,4,Dark,5,Black,1641,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,"Short, A-line dress in jersey with a round neckline and V-shaped opening at the front with narrow ties. Long, voluminous raglan sleeves and wide cuffs with covered buttons."

In [52]:
articles.isnull().sum()

article_id                      0
product_code                    0
prod_name                       0
product_type_no                 0
product_type_name               0
product_group_name              0
graphical_appearance_no         0
graphical_appearance_name       0
colour_group_code               0
colour_group_name               0
perceived_colour_value_id       0
perceived_colour_value_name     0
perceived_colour_master_id      0
perceived_colour_master_name    0
department_no                   0
department_name                 0
index_code                      0
index_name                      0
index_group_no                  0
index_group_name                0
section_no                      0
section_name                    0
garment_group_no                0
garment_group_name              0
detail_desc                     0
dtype: int64

In [53]:
articles.to_csv(
    "../../dataset/cleaned/articles_cleaned.csv",
    index=False
)

In [54]:
text_cols = articles.select_dtypes(include=["object", "string"]).columns

articles[text_cols] = articles[text_cols].apply(
    lambda col: col.str.strip()
)

In [55]:
articles.isnull().sum()

article_id                      0
product_code                    0
prod_name                       0
product_type_no                 0
product_type_name               0
product_group_name              0
graphical_appearance_no         0
graphical_appearance_name       0
colour_group_code               0
colour_group_name               0
perceived_colour_value_id       0
perceived_colour_value_name     0
perceived_colour_master_id      0
perceived_colour_master_name    0
department_no                   0
department_name                 0
index_code                      0
index_name                      0
index_group_no                  0
index_group_name                0
section_no                      0
section_name                    0
garment_group_no                0
garment_group_name              0
detail_desc                     0
dtype: int64

In [56]:
articles.to_csv(
    "../../dataset/cleaned/articles_cleaned.csv",
    index=False
)