In [51]:
import pandas as pd
import numpy as np

In [52]:
import os
os.getcwd()

'm:\\Portofolio_projects\\H&M_retail_Intelligence\\python\\data_cleaning'

In [53]:
pd.set_option('display.max_columns', None)

In [54]:
pd.set_option('display.max_colwidth', None)

In [55]:
customers = pd.read_csv("../../dataset/processed/customers_sample.csv")

In [56]:
customers.head()

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a91f8ca0d4b6efa8100
1,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801fe7fc0f26dd8d65a85a,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd4564743b005a805b1d
2,0000757967448a6cb83efb3ea7a3fb9d418ac7adf2379d8cd0c725276a467a2a,NaN,NaN,ACTIVE,NONE,20.0,fe7b8e2b3fafb89ca90db17ffeeae0fd29b795d803f74961cf8f27adb16e67e4
3,00007d2de826758b65a93dd24ce629ed66842531df6699338c5570910a014cc2,1.0,1.0,ACTIVE,Regularly,32.0,8d6f45050876d059c830a0fe63f1a4c022de279bb68ce312615afb86814fec7a
4,00009d946eec3ea54add5ba56d5210ea898def4b46c68570cf0096d962cacc75,1.0,1.0,ACTIVE,Regularly,56.0,b31984b20a8c478de38eaf113c581ff64e63c4242e607bbf2f3516b4ed40623d

In [57]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 272145 entries, 0 to 272144
Data columns (total 7 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   customer_id             272145 non-null  str
 1   FN                      111515 non-null  float64
 2   Active                  109622 non-null  float64
 3   club_member_status      271546 non-null  str
 4   fashion_news_frequency  270596 non-null  str
 5   age                     270671 non-null  float64
 6   postal_code             272145 non-null  str
dtypes: float64(3), str(4)
memory usage: 14.5 MB

In [58]:
print("="*60)
print("customers dataset overview")
print("="*60)

============================================================
customers dataset overview
============================================================

In [59]:
print(f"rows: {customers.shape[0]}")

rows: 272145

In [60]:
print(f"columns: {customers.shape[1]}")

columns: 7

In [61]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 272145 entries, 0 to 272144
Data columns (total 7 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   customer_id             272145 non-null  str
 1   FN                      111515 non-null  float64
 2   Active                  109622 non-null  float64
 3   club_member_status      271546 non-null  str
 4   fashion_news_frequency  270596 non-null  str
 5   age                     270671 non-null  float64
 6   postal_code             272145 non-null  str
dtypes: float64(3), str(4)
memory usage: 14.5 MB

In [62]:
missing=pd.DataFrame({
    "missing values":customers.isnull().sum(),
    "percentage":(
        customers.isnull().sum()/len(customers)*100
    ).round(2)
})
missing.sort_values("missing values", ascending=False)

                        missing values  percentage
Active                          162523       59.72
FN                              160630       59.02
fashion_news_frequency            1549        0.57
age                               1474        0.54
club_member_status                 599        0.22
customer_id                          0        0.00
postal_code                          0        0.00

In [63]:
customers.duplicated().sum()

np.int64(0)

In [64]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [65]:
customers.dtypes

customer_id                   str
FN                        float64
Active                    float64
club_member_status            str
fashion_news_frequency        str
age                       float64
postal_code                   str
dtype: object

In [66]:
customers["FN"].duplicated().sum()

np.int64(272143)

In [67]:
customers["age"].duplicated().sum()

np.int64(272064)

In [68]:
customers["age"].describe()

count    270671.000000
mean         35.941796
std          13.238801
min          16.000000
25%          25.000000
50%          31.000000
75%          48.000000
max          97.000000
Name: age, dtype: float64

In [69]:
customers["age"].value_counts().sort_index()

age
16.0      15
17.0     656
18.0    2265
19.0    4527
20.0    7879
        ...
91.0       4
92.0       1
93.0       1
95.0       2
97.0       1
Name: count, Length: 80, dtype: int64

In [70]:
customers["club_member_status"].value_counts(dropna=False)

club_member_status
ACTIVE        264067
PRE-CREATE      7408
NaN              599
LEFT CLUB         71
Name: count, dtype: int64

In [71]:
customers["fashion_news_frequency"].value_counts(dropna=False)

fashion_news_frequency
NONE         158774
Regularly    111717
NaN            1549
Monthly         105
Name: count, dtype: int64

In [72]:
customers["FN"].value_counts(dropna=False)

FN
NaN    160630
1.0    111515
Name: count, dtype: int64

In [73]:
customers["Active"].value_counts(dropna=False)

Active
NaN    162523
1.0    109622
Name: count, dtype: int64

In [74]:
customers['age']=customers['age'].fillna(customers['age'].median())

In [75]:
customers['club_member_status']=customers['club_member_status'].fillna("UNKNOWN")

In [76]:
customers['fashion_news_frequency']=customers['fashion_news_frequency'].fillna("none")

In [77]:
customers['FN']=customers['FN'].fillna(0).astype(int)

In [78]:
customers['Active']=customers['Active'].fillna(0).astype(int)

In [80]:
text_cols = customers.select_dtypes(include=["object", "string"]).columns

customers[text_cols] = customers[text_cols].apply(
    lambda col: col.str.strip()
)

In [81]:
customers.isnull().sum()

customer_id               0
FN                        0
Active                    0
club_member_status        0
fashion_news_frequency    0
age                       0
postal_code               0
dtype: int64

In [82]:
customers['FN'].value_counts(dropna=False)

FN
0    160630
1    111515
Name: count, dtype: int64

In [83]:
customers['Active'].value_counts(dropna=False)

Active
0    162523
1    109622
Name: count, dtype: int64

In [84]:
customers['club_member_status'].value_counts(dropna=False)

club_member_status
ACTIVE        264067
PRE-CREATE      7408
UNKNOWN          599
LEFT CLUB         71
Name: count, dtype: int64

In [85]:
customers['fashion_news_frequency'].value_counts(dropna=False)

fashion_news_frequency
NONE         158774
Regularly    111717
none           1549
Monthly         105
Name: count, dtype: int64

In [87]:
customers.to_csv("../../dataset/processed/customers_cleaned.csv", index=False)

In [3]:
import pandas as pd

customers = pd.read_csv("../../dataset/cleaned/customers_cleaned.csv")

customers["age"] = customers["age"].fillna(0).astype(int)

customers.to_csv(
    "../../dataset/cleaned/customers_cleaned.csv",
    index=False
)

print("Age column converted to integer.")

Age column converted to integer.