In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', None)

In [6]:
transactions = pd.read_csv('../../dataset/processed/transactions_sample.csv')

In [8]:
transactions.head()

,t_dat,customer_id,article_id,price,sales_channel_id
0,2019-09-13,215895f90002eb3d1a04bd603513c8e85e6002ef08f136...,786586001,0.022017,1
1,2019-02-23,7b183268e3a4623b80d5325ec4a20a0af0edff7bcb1748...,658911001,0.028797,2
2,2019-07-17,2eb7412239a90c0570cd3d1bf0492856ae5b59058b1ea6...,759326005,0.050831,2
3,2019-05-16,74f162e5a170fd57207aa2a7d5c58479ee9de903b2a277...,737137004,0.027102,1
4,2019-08-10,aab9306ee28c4db494003955f80355e540b01480ab35cf...,785931001,0.050831,2

In [9]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   t_dat             400000 non-null  str
 1   customer_id       400000 non-null  str
 2   article_id        400000 non-null  int64
 3   price             400000 non-null  float64
 4   sales_channel_id  400000 non-null  int64
dtypes: float64(1), int64(2), str(2)
memory usage: 15.3 MB

In [11]:
transactions.shape

(400000, 5)

In [12]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   t_dat             400000 non-null  str
 1   customer_id       400000 non-null  str
 2   article_id        400000 non-null  int64
 3   price             400000 non-null  float64
 4   sales_channel_id  400000 non-null  int64
dtypes: float64(1), int64(2), str(2)
memory usage: 15.3 MB

In [13]:
transactions.isnull().sum()

t_dat               0
customer_id         0
article_id          0
price               0
sales_channel_id    0
dtype: int64

In [14]:
transactions.duplicated().sum()

np.int64(685)

In [17]:
missing = pd.DataFrame({
    "Missing Values": transactions.isnull().sum(),
    "Percentage":
    (transactions.isnull().sum()/len(transactions)*100).round(2)
})

missing

                  Missing Values  Percentage
t_dat                          0         0.0
customer_id                    0         0.0
article_id                     0         0.0
price                          0         0.0
sales_channel_id               0         0.0

In [18]:
transactions.describe()

         article_id          price  sales_channel_id
count  4.000000e+05  400000.000000     400000.000000
mean   6.966687e+08       0.027828          1.704517
std    1.332195e+08       0.019051          0.456260
min    1.087750e+08       0.000169          1.000000
25%    6.331090e+08       0.015814          1.000000
50%    7.147900e+08       0.025407          2.000000
75%    7.870280e+08       0.033881          2.000000
max    9.562170e+08       0.506780          2.000000

In [21]:
transactions['t_dat'] =pd.to_datetime(
    transactions['t_dat']
)

In [22]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   t_dat             400000 non-null  datetime64[us]
 1   customer_id       400000 non-null  str
 2   article_id        400000 non-null  int64
 3   price             400000 non-null  float64
 4   sales_channel_id  400000 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 15.3 MB

In [25]:
transactions['price'].describe()

count    400000.000000
mean          0.027828
std           0.019051
min           0.000169
25%           0.015814
50%           0.025407
75%           0.033881
max           0.506780
Name: price, dtype: float64

In [26]:
transactions.to_csv('../../dataset/processed/transactions_cleaned.csv', index=False)

In [27]:
transactions.isnull().sum()

t_dat               0
customer_id         0
article_id          0
price               0
sales_channel_id    0
dtype: int64

In [28]:
transactions.duplicated().sum()

np.int64(685)